---

- name: Is Combine already installed?
  stat:
    path: /opt/combine
  register: combine_installed
  changed_when: combine_installed.stat.exists == False

- name: Clone Combine Github repository
  git:
    repo: https://github.com/WSULib/combine.git
    dest: /opt/combine
    version: "{{ combine_git_branch }}"
#  when: combine_installed.stat.exists == False

- name: Add localsettings.py
  template:
    src: localsettings.py
    dest: /opt/combine/combine/localsettings.py

- name: Set permissions
  file:
    path: /opt/combine
    recurse: yes
    owner: combine
    group: combine

- name: install latest version of libkrb5-dev
  package:
    name: libkrb5-dev
    state: latest
#  when: combine_installed.stat.exists == False

- name: Install Livy Client
  become_user: combine
  shell: |
    source /usr/local/anaconda/bin/activate combine
    pip install livy
  args:
    executable: /bin/bash
#  when: combine_installed.stat.exists == False

- name: Install es2csv to OS python 2.x
  shell: |
    source /usr/local/anaconda/bin/activate combine
    pip install git+https://github.com/MI-DPLA/es2csv.git@python3
  args:
    executable: /bin/bash
#  when: combine_installed.stat.exists == False

- name: Install combine mysql dependency
  package:
    name: libmysql-java
    state: latest
#  when: combine_installed.stat.exists == False

- name: Downgrade pip to 9.0.3
  become_user: combine
  shell: |
    source /usr/local/anaconda/bin/activate combine
    cd /opt/combine
    pip install pip==9.0.3
  args:
    executable: /bin/bash
#  when: combine_installed.stat.exists == False

- name: chown the whole conda env
  become: yes
  shell: |
    chown -R combine /usr/local/anaconda/envs/combine
  args:
    executable: /bin/bash

- name: Install Combine requirements
  become_user: combine
  shell: |
    source /usr/local/anaconda/bin/activate combine
    cd /opt/combine
    pip install -r requirements.txt
  args:
    executable: /bin/bash
  when: combine_installed.stat.exists == False

- name: Copy the combine.sql file to tmp
  template:
    src: combine.sql
    dest: /tmp/combine.sql
  when: combine_installed.stat.exists == False

- name: Prepare Combine Database
  mysql_db:
    config_file: /root/.my.cnf
    state: import
    name: all
    target: /tmp/combine.sql
  when: combine_installed.stat.exists == False

- name: Run Database migrations
  become_user: combine
  shell: |
    source /usr/local/anaconda/bin/activate combine
    python /opt/combine/manage.py makemigrations core
    python /opt/combine/manage.py migrate core
    python /opt/combine/manage.py migrate
    python /opt/combine/manage.py ensuremongocollections
  args:
    executable: /bin/bash
  when: combine_installed.stat.exists == False

- name: Create superuser
  shell: |
    source /usr/local/anaconda/bin/activate combine
    echo "from django.contrib.auth.models import User; User.objects.create_superuser('combine'"," 'root@none.com'"," '{{ django_combine_user_password }}')" | python /opt/combine/manage.py shell
  args:
    executable: /bin/bash
  when: combine_installed.stat.exists == False

- name: Collect static materials for Django
  shell: |
    source /usr/local/anaconda/bin/activate combine
    cd /opt/combine
    ./manage.py collectstatic
  args:
    executable: /bin/bash
  when: combine_installed.stat.exists == False

- name: Make directory that will hold avro files
  file:
    path: /home/combine/data/combine
    owner: combine
    group: combine
    mode: 0755
    recurse: yes
    state: directory
  when: combine_installed.stat.exists == False

- name: Set permissions
  shell: |
    chown -R combine:combine /opt/combine
  args:
    executable: /bin/bash
#  when: combine_installed.stat.exists == False
