---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
    - common
    - mysql
    - java
    - combine-elasticsearch
    - spark
    - ingestion3
    - livy
    - hadoop
    - mongo
    - supervisor
    - combine
    - gunicorn
    - nginx
